# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json
###

GET http://127.0.0.1:8000/hello/User
Accept: application/json
###

POST http://127.0.0.1:8000/exhibitors_find
Accept: application/json
Content-Type: application/json

{
    "exhibitorName": "ADEL CORP "
}
###

POST http://127.0.0.1:8000/csv/clean_missing_description
Accept: application/json
Content-Type: application/json

{
  "csv_path": "exhibitors.csv",
  "out_csv_path": "exhibitors_cleaned.csv"
}
###

POST http://127.0.0.1:8000/enrich_exhibitors/run
Content-Type: application/json

{
  "csv_path": "exhibitors_cleaned.csv",
  "out_json_path": "exhibitors_enriched.json",
  "out_csv_path": "exhibitors_enriched.csv",
  "name_col": "exhibitorName",
  "delay_seconds": 0.2,
  "verbose": true
}
####

### Limpieza de json por sectores; crea un nuevo json exhibitors_filtered
POST http://127.0.0.1:8000/utils/filter-sectors
Accept: application/json

###

### Llamada para el buscador de webs (Antonio)
POST http://127.0.0.1:8000/test/run_antonio_workflow
Content-Type: application/json

{
  "input_file": "exhibitors_filtered.json",
  "output_file": "exhibitor_webs.json"
}
####

### Enriquecer el JSON existente con IDs de Apollo.io
# Este endpoint abre 'exhibitors_webs.json' y le inyecta los IDs encontrados.
POST http://127.0.0.1:8000/enrich/apollo_ids
Accept: application/json
Content-Type: application/json

{}
####

### Rellena de nombres, emails, linkedin de los contactos
POST http://127.0.0.1:8000/enrich/apollo_contacts_details
Accept: application/json
Content-Type: application/json

{}
####

